(cl:defpackage people_msgs-msg
  (:use )
  (:export
   "<PERSON>"
   "PERSON"
   "<PEOPLEPREDICTION>"
   "PEOPLEPREDICTION"
   "<POSITIONMEASUREMENTARRAY>"
   "POSITIONMEASUREMENTARRAY"
   "<PEOPLE>"
   "PEOPLE"
   "<PERSONSTAMPED>"
   "PERSONSTAMPED"
   "<POSITIONMEASUREMENT>"
   "POSITIONMEASUREMENT"
  ))

